[workspace]
members = [
    "contracts/cosmwasm-vm/cw-icon-light-client",
    "contracts/cosmwasm-vm/cw-xcall",
    "contracts/cosmwasm-vm/cw-ibc-core",
    "contracts/cosmwasm-vm/cw-common",
    "libraries/rust/common",
    "contracts/cosmwasm-vm/cw-mock-dapp",
    "contracts/cosmwasm-vm/cw-mock-ibc-core",
    "contracts/cosmwasm-vm/cw-xcall-ibc-connection",
     "contracts/cosmwasm-vm/cw-xcall-app",
     "contracts/cosmwasm-vm/cw-integration",
     "contracts/cosmwasm-vm/cw-ibc-client",
]

[workspace.package]
authors = ["Icon Foundation<foo@icon.foundation>"]
repository = "https://github.com/icon-project/ibc-integration.git"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
