[workspace]
members = [
    "contracts/cosmwasm-vm/cw-icon-light-client",
    "contracts/cosmwasm-vm/cw-xcall",
    "contracts/cosmwasm-vm/cw-ibc-core",
    "contracts/cosmwasm-vm/cw-common",
    "libraries/rust/common",
    "contracts/cosmwasm-vm/cw-mock-dapp",
    "contracts/cosmwasm-vm/cw-mock-ibc-core",
    "contracts/cosmwasm-vm/cw-xcall-ibc-connection",
     "contracts/cosmwasm-vm/cw-xcall-app",
     "contracts/cosmwasm-vm/cw-integration",
     "contracts/cosmwasm-vm/cw-mock-dapp-multi",
]

[workspace.package]
authors = ["Icon Foundation<foo@icon.foundation>"]
repository = "https://github.com/icon-project/ibc-integration.git"

[workspace.dependencies]
cosmwasm-std = {version="1.2.2",default-features = false}
cosmwasm-storage = "1.2.2"
cosmwasm-schema = "1.2.2"
schemars = "0.8.12"
cw-storage-plus = "1.0.1"
cw2 = "1.0.1"

ibc-proto = { version = "0.26.0", default-features = false}
prost = { version = "0.11.8", default-features = false,features=["prost-derive"]}

serde-json-wasm = {version="0.5.0", default-features = false}
serde_json = "1.0.96"
serde = { version = "1.0.154", default-features = false, features = ["derive"] }

bytes = { version = "1.4.0", default-features = false }
thiserror = { version = "1.0.39" }
hex ={ version = "0.4.3", default-features = false }

[profile.release]
opt-level = 'z'
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
