[profile.default]
build_info = true
extra_output = ["storageLayout"]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"


[rpc_endpoints]
local = "${LOCAL_RPC_URL}" 
sepolia = "${SEPOLIA_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
fuji = "${FUJI_RPC_URL}"
arbitrum_goerli = "${ARBITRUM_GOERLI_RPC_URL}"
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"

ethereum= "${ETHEREUM_RPC_URL}"
binance= "${BSC_RPC_URL}"
avalanche= "${AVALANCHE_RPC_URL}"
# arbitrum=
# optimism=
# base=

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}"}
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain="bsc-testnet"}
fuji = { key = "${SNOWSCAN_API_KEY}"}
arbitrum_goerli = { key = "${ARBITRUMSCAN_API_KEY}"}
optimism_goerli = { key = "${OPTIMISMSCAN_API_KEY}"}
base_goerli = { key = "${BASESCAN_API_KEY}"}

ethereum={ key = "${ETHERSCAN_API_KEY}", chain="mainnet"}
binance={ key = "${BSCSCAN_API_KEY}", chain="bsc"}
avalanche={ key = "${SNOWSCAN_API_KEY}", chain="avalanche"}
# arbitrum=
# optimism=
# base=
