on:
  push:
    branches:
      - main
    paths:
      - ".github/packer/*"

jobs:
  start-runner:
    uses: ./.github/workflows/runner-start.yml
    secrets: inherit
  build:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    defaults:
      run:
        working-directory: ./.github/packer
    env:
      PRODUCT_VERSION: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `packer init`
        id: init
        run: "packer init ."
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
      - name: Build and Publish AMI
        run: packer build -color=false .
  stop-runner:
    uses: ./.github/workflows/runner-stop.yml
    secrets: inherit
    with:
      label: ${{ needs.start-runner.outputs.label }}
      ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
    needs:
      - start-runner
      - build
