name: Deploy Contracts After PR Merge to main branch

on:
  push:
    branches:
      - "main"
      - "fix/deployment-to-uat"

jobs:
  deploy-contracts-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve the secret and decode it to a file
        working-directory: contracts/javascore
        env:
          UAT_KEYSTORE_B64: ${{ secrets.UAT_KEYSTORE_B64 }}
          UAT_PASSWD: ${{ secrets.UAT_PASSWD }}
          UAT_KEYSTORE: ./key.json
        run: echo $UAT_KEYSTORE_B64 | base64 -d > key.json

      - name: Deploy all contracts on UAT environment
        run: cd contracts/javascore && ./gradlew clean build && ./gradlew optimizedJar && ./gradlew deployToUat -PdeploymentENV=uat -PkeystoreName=$UAT_KEYSTORE -PkeystorePass=$UAT_PASSWD
